### ISSUE TITLE
KELIP guided diffusion

### ISSUE THREAD

**Issue by epicure** [navervision/KELIP#1]
Thanks for the KELIP! If KELIP can be used with the diffusion model (like CLIP) in Korean, it will be very interesting.

I tried [CLIP Guided Diffusion](https://colab.research.google.com/drive/12a_Wrfi2_gwwAuN3VvMTwVMz9TfqctNj) and [Disco Diffusion v5](https://colab.research.google.com/drive/12a_Wrfi2_gwwAuN3VvMTwVMz9TfqctNj). Here I simply substituted CLIP with KELIP. But, the result was not good.

![image](https://user-images.githubusercontent.com/422362/160945250-68005a45-ab57-4762-99a6-8fd5edd36a03.png)

I chose Disco Diffusion v5 to investigate more.

Both CLIP and KELIP used VITB32 only for this testing. For the default prompt "A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation" It gets these images.
![image](https://user-images.githubusercontent.com/422362/160945527-466611ba-551b-4e6c-a8a4-686792835658.png)

For the prompt "A cute cat" with the same setting.
![image](https://user-images.githubusercontent.com/422362/160945550-e1275304-11e9-4dbf-a41e-74291d4ce54d.png)

And for "한 폭의 바다를 비추는 단 하나의 등대의 아름다운 그림, 이중섭 그림"  translation: "A beautiful picture of a single lighthouse shining on the sea, Lee Jung Sub's picture."
![image](https://user-images.githubusercontent.com/422362/160945580-063ec017-b766-4cba-81b4-db356a75eb27.png)

I added "kelip" in "clip_models" in "2. Diffusion and CLIP model settings" in Disco Diffusion v5.

Could "l2norm" argument causes this issues? I used ```encode_image, encode_text``` in the default setting. 

Since we can see the diffusion model as a brush and the CLIP like model as the painter. I couldn't find out which is the reason for this issue "data distribution in ImageNet" that the diffusion model learned or "KELIP with improper settings"

Thanks again for the great effort!

**Comment by geonm** [comment]
Thanks for your interest.

### Q: Could "l2norm" argument causes this issues? I used encode_image, encode_text in the default setting.

\>> If you used `l2norm=False`, the default setting, it would work as CLIP `encode_image` and `encode_text` API.


Retrieved images through our internally used KELIP search demo are as follows:
+ NOTE: Areca palm photo does not affect results. 

### Prompt: A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation
![image](https://user-images.githubusercontent.com/21214529/160954880-a7c84a74-c5d0-4ad2-8470-24dba617c1cd.png)

### Prompt: greg rutkowski and thomas kinkade, Trending on artstation
![image](https://user-images.githubusercontent.com/21214529/160955639-467f5466-fb2c-44a1-8cbb-375cb73bbafa.png)

### Prompt: a cute cat
![image](https://user-images.githubusercontent.com/21214529/160956202-79a69ee1-9cc2-47f4-a1a9-5df43858ca15.png)

### Prompt: 한 폭의 바다를 비추는 단 하나의 등대의 아름다운 그림, 이중섭 그림
![image](https://user-images.githubusercontent.com/21214529/160955688-684f4b11-68e4-472f-b63c-e8d85c0840b1.png)

### Prompt: 이중섭 그림
![image](https://user-images.githubusercontent.com/21214529/160955718-42da2319-6fa5-4260-b03c-eb749c756568.png)

### Prompt: 박수근이 그린 고양이
![image](https://user-images.githubusercontent.com/21214529/160955791-0ab37b36-bfc4-44b7-a617-90cc3f5b3b19.png)

### Prompt: 박수근 화백
![image](https://user-images.githubusercontent.com/21214529/160955809-41a78240-dd9d-4525-bb86-1c6490674a7e.png)

+ Above results show our KELIP model is learned about most of the prompts you used.
+ The reason for this phenomenon seems very diverse. It's interesting.

**Comment by kobiso** [comment]
Thanks @epicure for your interest in KELIP :)

We used [afiaka87/clip-guided-diffusion](https://github.com/afiaka87/clip-guided-diffusion) for KELIP guided diffusion, basically it is the same with what you used.
We did not use l2 normalization for generating images, so I'm guessing the cause can be different factor.
I'll try the same prompts and see if our implementation had the similar issue.

**Comment by epicure** [comment]
It's working now! The problem was that I didn't use the KELIP's tokenizer but the CLIP's tokenizer. Thanks to your various examples, I was able to find mistakes.

- left: CLIP (ViT-B/32), "A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation."
- middle: KELIP (ViT-B/32), "A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation."
- right: KELIP (ViT-B/32), "한 폭의 바다를 비추는 단 하나의 등대의 아름다운 그림, 이중섭 그림"

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/422362/160991175-7902961f-8fe2-4e05-9723-7522efe9e698.png">

When I used KELIP it was little slower than CLIP for now. Is this because of the size of parameters? Anyway...

I am very glad to be able to guide the diffusion model in Korean. If students and creators use it, it will open up new possibilities. I'm currently one of Clova Studio's beta users and one of [MidJourney](https://twitter.com/midjourney)'s beta users who is very interested in the assisted writing & drawing.

I was trying doing something like Ryan Moulton's Articles
- https://moultano.wordpress.com/2021/07/20/tour-of-the-sacred-library 
- https://moultano.wordpress.com/2022/03/24/depth-of-field 
in Korean to explore its potential for the education etc. KELIP could be vey helpful in this context.

And "KELIP search demo" looks promising too! This reminds me of https://knn5.laion.ai which helps users when they are doing the prompt programming. 

Thank you very much for replying. And I hope to see many people use KELIP to do something great!

**Comment by geonm** [comment]
"Text to Image" is always cool.

Thanks.

### Q: When I used KELIP it was little slower than CLIP for now. Is this because of the size of parameters?
=> No. KELIP and CLIP are the same except for text token embeddings. I will check it later.

**Comment by kobiso** [comment]
I'm glad you solve the problem and thank you for sharing the results 👍 
About the question _"When I used KELIP it was little slower than CLIP for now. Is this because of the size of parameters?"_, I'm guessing it is because KELIP has vocabulary size of 98818 when CLIP has vocabulary size of 49408 and this will cause parameter difference.
To be specific,
```
# KELIP (ViT-B/16)
Model parameters: 176,575,233
Input resolution: 224
Context length: 77
Vocab size: 98818

# CLIP (ViT-B/16)
Model parameters: 151,277,313
Input resolution: 224
Context length: 77
Vocab size: 49408
```

Your project seems very interesting, and it would be great if you share interesting results using KELIP afterward :)
